site_name: Marketingmethoden
site_url: https://mydomain.org/mysite
theme:
  name: material
  language: de

nav:
- Informationen zur LV: index.md
- Korrelation & Regression: regression.md
- t-Test & Varianzanalyse: gruppenvergleiche.md
- Mediation: mediation.md
- Moderation: moderation.md

extra_css:
  - custom.css