site_name: Marketingmethoden
site_url: https://mydomain.org/mysite
theme:
  name: material

  features:
    - navigation.sections
    - toc.integrate: false  # Deaktiviert das automatische Inhaltsverzeichnis